name: start
version: 0.0.9+2
author: Yehor Lvivski <lvivski@gmail.com>
description: Sinatra inspired Web framework
homepage: http://github.com/lvivski/start
dependencies:
  browser: any
  unittest: '>=0.2.7'
